### ISSUE TITLE
fill .gitignore

### ISSUE THREAD

**Issue by BorjaEst** [PCP2024/PCPuppies#3]
I recommend you this link:
https://github.com/github/gitignore/blob/main/Python.gitignore

Also add [.DS_Store](https://github.com/PCP2024/PCPuppies/blob/main/.DS_Store) to the .gitignore.

**Comment by Hctor99** [comment]
Thank you Borja!

**Comment by BorjaEst** [comment]
You still need to complete it, with all the files from the link I added. Other wise, your repository will still collect files which are not supposed to be in the repository.

for example here:
https://github.com/PCP2024/PCPuppies/tree/main/tests

The __pycache__ is your cache execution. Almost every time you run, it is going  to run it is going to regenerate, and if you version control this files (with git) then your repositry size will grow a lot (and you do not needed as software).

.gitignore prevents this kind of things.

**Comment by BorjaEst** [comment]
Just copy the whole file form "https://github.com/github/gitignore/blob/main/Python.gitignore" and add your specifics at the bottom. And do not forget to remove all the __pycache__ folders that were added to your repository!
